# Generated by Django 5.2.16 on 2026-07-11 19:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('RECEBIDO', 'Recebido'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_MP', 'Aguardando MP'), ('PROGRAMADO', 'Programado'), ('EM_PRODUCAO', 'Em produção'), ('CQ', 'Controle de qualidade'), ('FINALIZADO', 'Finalizado'), ('EXPEDIDO', 'Expedido'), ('CANCELADO', 'Cancelado')], default='RECEBIDO', max_length=20, verbose_name='status')),
                ('prazo', models.DateField(help_text='Data combinada com o cliente para a entrega.', verbose_name='prazo de entrega')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='cadastros.cliente', verbose_name='cliente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('status_anterior', models.CharField(blank=True, choices=[('RECEBIDO', 'Recebido'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_MP', 'Aguardando MP'), ('PROGRAMADO', 'Programado'), ('EM_PRODUCAO', 'Em produção'), ('CQ', 'Controle de qualidade'), ('FINALIZADO', 'Finalizado'), ('EXPEDIDO', 'Expedido'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='status anterior')),
                ('status_novo', models.CharField(blank=True, choices=[('RECEBIDO', 'Recebido'), ('EM_ANALISE', 'Em análise'), ('AGUARDANDO_MP', 'Aguardando MP'), ('PROGRAMADO', 'Programado'), ('EM_PRODUCAO', 'Em produção'), ('CQ', 'Controle de qualidade'), ('FINALIZADO', 'Finalizado'), ('EXPEDIDO', 'Expedido'), ('CANCELADO', 'Cancelado')], max_length=20, verbose_name='status novo')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'histórico do pedido',
                'verbose_name_plural': 'históricos do pedido',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_pedido', to='cadastros.produto', verbose_name='produto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.pedido', verbose_name='pedido')),
            ],
            options={
                'verbose_name': 'item do pedido',
                'verbose_name_plural': 'itens do pedido',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('pedido', 'produto'), name='item_produto_unico_por_pedido', violation_error_message='Este produto já está no pedido.')],
            },
        ),
    ]
