# Generated by Django 5.2.16 on 2026-07-11 19:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Programacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('data', models.DateField(verbose_name='data programada')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motivo_remocao', models.TextField(blank=True, verbose_name='motivo da remoção')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='cadastros.equipamento', verbose_name='equipamento')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to='pedidos.itempedido', verbose_name='item do pedido')),
                ('operador', models.ForeignKey(blank=True, help_text='Pode ser definido depois, antes da produção.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programacoes', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
            ],
            options={
                'verbose_name': 'programação',
                'verbose_name_plural': 'programações',
                'ordering': ['data', 'equipamento__nome', 'id'],
                'indexes': [models.Index(fields=['data', 'ativo'], name='pcp_program_data_685601_idx')],
            },
        ),
    ]
