# Generated by Django 5.2.16 on 2026-07-13 02:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('nome', models.CharField(help_text='Identificação da versão. Ex.: “Padrão”, “v2 sem parabenos”.', max_length=60, verbose_name='nome')),
                ('rendimento', models.DecimalField(decimal_places=3, help_text='Quantidade de produto que esta fórmula produz (na unidade do produto).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='rendimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='formulas', to='cadastros.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'fórmula',
                'verbose_name_plural': 'fórmulas',
                'ordering': ['produto__nome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ComponenteFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, help_text='Quantidade para o rendimento base da fórmula.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('embalagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_formulas', to='cadastros.embalagem', verbose_name='embalagem')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usos_em_formulas', to='cadastros.materiaprima', verbose_name='matéria-prima')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='ordens.formula', verbose_name='fórmula')),
            ],
            options={
                'verbose_name': 'componente da fórmula',
                'verbose_name_plural': 'componentes da fórmula',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrdemProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade prevista')),
                ('data_programada', models.DateField(verbose_name='data programada')),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('LIBERADA', 'Liberada'), ('EM_PRODUCAO', 'Em produção'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='RASCUNHO', max_length=20, verbose_name='status')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('motivo_cancelamento', models.TextField(blank=True, verbose_name='motivo do cancelamento')),
                ('liberado_em', models.DateTimeField(blank=True, null=True, verbose_name='liberada em')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('equipamento', models.ForeignKey(blank=True, help_text='Obrigatório para liberar a OP.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='cadastros.equipamento', verbose_name='equipamento')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='ordens.formula', verbose_name='fórmula')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='pedidos.itempedido', verbose_name='item do pedido')),
                ('liberado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='liberada por')),
                ('operador', models.ForeignKey(blank=True, help_text='Obrigatório para liberar a OP.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_como_operador', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
            ],
            options={
                'verbose_name': 'ordem de produção',
                'verbose_name_plural': 'ordens de produção',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MaterialOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_necessaria', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade necessária')),
                ('embalagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.embalagem', verbose_name='embalagem')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.materiaprima', verbose_name='matéria-prima')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais', to='ordens.ordemproducao', verbose_name='ordem de produção')),
            ],
            options={
                'verbose_name': 'material da OP',
                'verbose_name_plural': 'materiais da OP',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='HistoricoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='ordens.ordemproducao', verbose_name='ordem de produção')),
            ],
            options={
                'verbose_name': 'histórico da OP',
                'verbose_name_plural': 'históricos da OP',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(fields=('produto', 'nome'), name='formula_nome_unico_por_produto', violation_error_message='Este produto já tem uma fórmula com esse nome.'),
        ),
        migrations.AddConstraint(
            model_name='componenteformula',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima__isnull', False), ('embalagem__isnull', True)), models.Q(('materia_prima__isnull', True), ('embalagem__isnull', False)), _connector='OR'), name='componente_exatamente_um_item'),
        ),
        migrations.AddConstraint(
            model_name='materialop',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima__isnull', False), ('embalagem__isnull', True)), models.Q(('materia_prima__isnull', True), ('embalagem__isnull', False)), _connector='OR'), name='material_op_exatamente_um_item'),
        ),
    ]
