# Generated by Django 5.2.16 on 2026-07-19 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_lote_lote_fornecedor_alter_lote_codigo_sequencialote'),
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='lote_produto',
            field=models.ForeignKey(blank=True, help_text='Lote interno reservado automaticamente na liberação da OP e confirmado na conclusão da produção.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_de_producao', to='estoque.lote', verbose_name='lote do produto acabado'),
        ),
    ]
