# Generated by Django 5.2.16 on 2026-07-19 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        ('ordens', '0002_ordemproducao_lote_produto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSnapshotFormulaOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_codigo', models.CharField(max_length=30, verbose_name='código do item')),
                ('item_nome', models.CharField(max_length=150, verbose_name='nome do item')),
                ('item_unidade', models.CharField(blank=True, max_length=20, verbose_name='unidade')),
                ('quantidade_teorica', models.DecimalField(decimal_places=3, help_text='Para o rendimento base da fórmula.', max_digits=12, verbose_name='quantidade teórica')),
                ('quantidade_escalada', models.DecimalField(decimal_places=3, help_text='Para a quantidade prevista da OP.', max_digits=12, verbose_name='quantidade escalada')),
            ],
            options={
                'verbose_name': 'item do snapshot da fórmula',
                'verbose_name_plural': 'itens do snapshot da fórmula',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SnapshotFormulaOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome da fórmula')),
                ('versao', models.PositiveIntegerField(verbose_name='versão')),
                ('data_versao', models.DateTimeField(blank=True, help_text='Quando esta versão da fórmula entrou em vigor.', null=True, verbose_name='data da versão')),
                ('rendimento', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='rendimento')),
                ('instrucoes', models.TextField(blank=True, verbose_name='instruções de fabricação')),
                ('congelado_em', models.DateTimeField(auto_now_add=True, verbose_name='congelado em')),
            ],
            options={
                'verbose_name': 'snapshot da fórmula da OP',
                'verbose_name_plural': 'snapshots da fórmula das OPs',
                'ordering': ['-congelado_em'],
            },
        ),
        migrations.AlterModelOptions(
            name='formula',
            options={'ordering': ['produto__nome', 'nome', '-versao'], 'verbose_name': 'fórmula', 'verbose_name_plural': 'fórmulas'},
        ),
        migrations.RemoveConstraint(
            model_name='formula',
            name='formula_nome_unico_por_produto',
        ),
        migrations.AddField(
            model_name='formula',
            name='aprovada_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='aprovada em'),
        ),
        migrations.AddField(
            model_name='formula',
            name='aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='aprovada por'),
        ),
        migrations.AddField(
            model_name='formula',
            name='status',
            field=models.CharField(choices=[('VIGENTE', 'Vigente'), ('HISTORICA', 'Histórica')], default='VIGENTE', max_length=10, verbose_name='situação da versão'),
        ),
        migrations.AddField(
            model_name='formula',
            name='versao',
            field=models.PositiveIntegerField(default=1, verbose_name='versão'),
        ),
        migrations.AlterField(
            model_name='formula',
            name='nome',
            field=models.CharField(help_text='Identificação da fórmula. Ex.: “Padrão”, “Sem parabenos”.', max_length=60, verbose_name='nome'),
        ),
        migrations.AddConstraint(
            model_name='formula',
            constraint=models.UniqueConstraint(fields=('produto', 'nome', 'versao'), name='formula_nome_versao_unicos_por_produto', violation_error_message='Este produto já tem esta versão da fórmula.'),
        ),
        migrations.AddField(
            model_name='itemsnapshotformulaop',
            name='embalagem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.embalagem', verbose_name='embalagem'),
        ),
        migrations.AddField(
            model_name='itemsnapshotformulaop',
            name='materia_prima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.materiaprima', verbose_name='matéria-prima'),
        ),
        migrations.AddField(
            model_name='snapshotformulaop',
            name='congelado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='congelado por'),
        ),
        migrations.AddField(
            model_name='snapshotformulaop',
            name='formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='ordens.formula', verbose_name='fórmula de origem'),
        ),
        migrations.AddField(
            model_name='snapshotformulaop',
            name='ordem',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_formula', to='ordens.ordemproducao', verbose_name='ordem de produção'),
        ),
        migrations.AddField(
            model_name='itemsnapshotformulaop',
            name='snapshot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='ordens.snapshotformulaop', verbose_name='snapshot'),
        ),
        migrations.AddConstraint(
            model_name='itemsnapshotformulaop',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('materia_prima__isnull', False), ('embalagem__isnull', True)), models.Q(('materia_prima__isnull', True), ('embalagem__isnull', False)), _connector='OR'), name='item_snapshot_exatamente_um_item'),
        ),
    ]
