# Generated by Django 5.2.16 on 2026-07-20 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        ('ordens', '0003_itemsnapshotformulaop_snapshotformulaop_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemproducao',
            name='linha',
            field=models.ForeignKey(blank=True, help_text='Setor/linha onde a OP será executada.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens', to='cadastros.setor', verbose_name='linha de produção'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='prazo',
            field=models.DateField(blank=True, help_text='Data limite para concluir a produção.', null=True, verbose_name='prazo'),
        ),
        migrations.AddField(
            model_name='ordemproducao',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ordens_como_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='supervisor'),
        ),
    ]
