# Generated by Django 5.2.16 on 2026-07-20 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_equipamento_calibracao_validade_and_more'),
        ('ordens', '0004_op_linha_supervisor_prazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaSnapshotOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(verbose_name='sequência')),
                ('instrucao', models.TextField(verbose_name='instrução')),
                ('material_codigo', models.CharField(blank=True, max_length=30, verbose_name='material adicionado')),
                ('temperatura_prevista', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='temperatura prevista (°C)')),
                ('tempo_previsto_min', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='tempo previsto (min)')),
                ('velocidade_prevista', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='velocidade prevista (rpm)')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ordens.snapshotformulaop', verbose_name='snapshot')),
            ],
            options={
                'verbose_name': 'etapa do snapshot da OP',
                'verbose_name_plural': 'etapas do snapshot da OP',
                'ordering': ['sequencia', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EtapaFormula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencia', models.PositiveIntegerField(verbose_name='sequência')),
                ('instrucao', models.TextField(verbose_name='instrução')),
                ('temperatura_prevista', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='temperatura prevista (°C)')),
                ('tempo_previsto_min', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='tempo previsto (min)')),
                ('velocidade_prevista', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='velocidade prevista (rpm)')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ordens.formula', verbose_name='fórmula')),
                ('materia_prima', models.ForeignKey(blank=True, help_text='Opcional: material adicionado nesta etapa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.materiaprima', verbose_name='material adicionado')),
            ],
            options={
                'verbose_name': 'etapa da fórmula',
                'verbose_name_plural': 'etapas da fórmula',
                'ordering': ['formula_id', 'sequencia', 'id'],
                'constraints': [models.UniqueConstraint(fields=('formula', 'sequencia'), name='etapa_sequencia_unica_por_formula', violation_error_message='Já existe uma etapa com essa sequência.')],
            },
        ),
    ]
