# Generated by Django 5.2.16 on 2026-07-13 12:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('ordens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExecucaoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('iniciado_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início da produção')),
                ('concluido_em', models.DateTimeField(blank=True, null=True, verbose_name='fim da produção')),
                ('quantidade_produzida', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade produzida')),
                ('perdas', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='perdas')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('concluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='concluída por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('iniciado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='iniciada por')),
                ('lote_produzido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='estoque.lote', verbose_name='lote do produto acabado')),
                ('ordem', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='execucao', to='ordens.ordemproducao', verbose_name='ordem de produção')),
            ],
            options={
                'verbose_name': 'execução da produção',
                'verbose_name_plural': 'execuções da produção',
                'ordering': ['-iniciado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='FotoProducao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(help_text='Foto do processo (JPG, PNG ou WEBP).', upload_to='producao/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])], verbose_name='arquivo')),
                ('descricao', models.CharField(blank=True, max_length=120, verbose_name='descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='producao.execucaoop', verbose_name='execução')),
            ],
            options={
                'verbose_name': 'foto da produção',
                'verbose_name_plural': 'fotos da produção',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='producao.execucaoop', verbose_name='execução')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'ocorrência',
                'verbose_name_plural': 'ocorrências',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Parada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('MANUTENCAO', 'Manutenção'), ('FALTA_MATERIAL', 'Falta de material'), ('SETUP', 'Setup / troca'), ('LIMPEZA', 'Limpeza'), ('REFEICAO', 'Refeição / intervalo'), ('FALTA_OPERADOR', 'Falta de operador'), ('OUTRO', 'Outro')], max_length=20, verbose_name='motivo')),
                ('inicio', models.DateTimeField(default=django.utils.timezone.now, verbose_name='início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='observações')),
                ('execucao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradas', to='producao.execucaoop', verbose_name='execução')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrada por')),
            ],
            options={
                'verbose_name': 'parada',
                'verbose_name_plural': 'paradas',
                'ordering': ['-inicio', '-id'],
            },
        ),
    ]
