# Generated by Django 5.2.16 on 2026-07-19 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0002_ordemproducao_lote_produto'),
        ('producao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atividade', models.CharField(choices=[('LIBERACAO', 'Liberação da OP'), ('ATRIBUICAO_LOTE', 'Atribuição de lote'), ('SEPARACAO', 'Separação de materiais'), ('PRODUCAO', 'Produção'), ('ENVASE', 'Envase'), ('CONFERENCIA', 'Conferência'), ('OUTRO', 'Outro')], max_length=20, verbose_name='atividade')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades_de_op', to=settings.AUTH_USER_MODEL, verbose_name='funcionário')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atividades', to='ordens.ordemproducao', verbose_name='ordem de produção')),
            ],
            options={
                'verbose_name': 'atividade da OP',
                'verbose_name_plural': 'atividades da OP',
                'ordering': ['data', 'id'],
            },
        ),
    ]
