# Generated by Django 5.2.16 on 2026-07-19 20:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_lote_lote_fornecedor_alter_lote_codigo_sequencialote'),
        ('ordens', '0003_itemsnapshotformulaop_snapshotformulaop_and_more'),
        ('producao', '0002_atividadeop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoMaterialOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.localestoque', verbose_name='local de origem')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos_em_op', to='estoque.lote', verbose_name='lote')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumos', to='ordens.materialop', verbose_name='material da OP')),
                ('movimentacao', models.ForeignKey(blank=True, help_text='Preenchida na conclusão da OP — confirma a baixa do estoque.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.movimentacao', verbose_name='movimentação de saída')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'consumo de material da OP',
                'verbose_name_plural': 'consumos de material da OP',
                'ordering': ['material_id', 'lote__validade', 'id'],
            },
        ),
    ]
