# Generated by Django 5.2.16 on 2026-07-20 19:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_materiaprima_critico_balanca'),
        ('estoque', '0003_lote_situacao'),
        ('ordens', '0004_op_linha_supervisor_prazo'),
        ('producao', '0003_consumomaterialop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PesagemOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_prevista', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='quantidade prevista')),
                ('quantidade_pesada', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='quantidade pesada')),
                ('tolerancia_percentual', models.DecimalField(decimal_places=3, default=Decimal('1'), max_digits=6, verbose_name='tolerância (%)')),
                ('etiqueta', models.CharField(blank=True, max_length=60, verbose_name='identificação da etiqueta')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('balanca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='cadastros.balanca', verbose_name='balança')),
                ('conferente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='conferente')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='estoque.lote', verbose_name='lote pesado')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesagens', to='ordens.materialop', verbose_name='material da OP')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
            ],
            options={
                'verbose_name': 'pesagem da OP',
                'verbose_name_plural': 'pesagens da OP',
                'ordering': ['data', 'id'],
            },
        ),
    ]
