# Generated by Django 5.2.16 on 2026-07-20 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_equipamento_calibracao_validade_and_more'),
        ('ordens', '0004_op_linha_supervisor_prazo'),
        ('producao', '0004_pesagemop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistEquipamentoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PRE_USO', 'Pré-uso'), ('POS_USO', 'Pós-uso')], max_length=10, verbose_name='tipo')),
                ('itens_verificados', models.TextField(blank=True, verbose_name='itens verificados')),
                ('condicao_final', models.CharField(blank=True, max_length=120, verbose_name='condição final')),
                ('danos', models.TextField(blank=True, verbose_name='danos identificados')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.equipamento', verbose_name='equipamento')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checklists_equipamento', to='ordens.ordemproducao', verbose_name='ordem de produção')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável pela liberação')),
            ],
            options={
                'verbose_name': 'checklist de equipamento da OP',
                'verbose_name_plural': 'checklists de equipamento da OP',
                'ordering': ['data', 'id'],
            },
        ),
    ]
