# Generated by Django 5.2.16 on 2026-07-20 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_etapasnapshotop_etapaformula'),
        ('producao', '0005_checklistequipamentoop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_real', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='temperatura real (°C)')),
                ('tempo_real_min', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True, verbose_name='tempo real (min)')),
                ('velocidade_real', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='velocidade real (rpm)')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('termino', models.DateTimeField(blank=True, null=True, verbose_name='término')),
                ('pulada', models.BooleanField(default=False, verbose_name='etapa pulada')),
                ('justificativa', models.TextField(blank=True, verbose_name='justificativa')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('conferente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='conferente')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='ordens.etapasnapshotop', verbose_name='etapa da fórmula')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etapas_execucao', to='ordens.ordemproducao', verbose_name='ordem de produção')),
            ],
            options={
                'verbose_name': 'etapa executada da OP',
                'verbose_name_plural': 'etapas executadas da OP',
                'ordering': ['etapa__sequencia', 'id'],
                'constraints': [models.UniqueConstraint(fields=('ordem', 'etapa'), name='etapa_op_unica_por_ordem')],
            },
        ),
    ]
