# Generated by Django 5.2.16 on 2026-07-20 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_equipamento_calibracao_validade_and_more'),
        ('ordens', '0005_etapasnapshotop_etapaformula'),
        ('producao', '0006_etapaop'),
        ('qualidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControleProcessoOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='limite mínimo aplicado')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='limite máximo aplicado')),
                ('resultado', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='resultado')),
                ('resultado_texto', models.CharField(blank=True, max_length=200, verbose_name='resultado descritivo')),
                ('metodo', models.CharField(blank=True, max_length=120, verbose_name='método')),
                ('fora_especificacao', models.BooleanField(default=False, verbose_name='fora da especificação')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('analista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='analista')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.equipamento', verbose_name='equipamento')),
                ('etapa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='controles', to='ordens.etapasnapshotop', verbose_name='etapa')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_processo', to='ordens.ordemproducao', verbose_name='ordem de produção')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='qualidade.tipoanalise', verbose_name='parâmetro')),
            ],
            options={
                'verbose_name': 'controle em processo da OP',
                'verbose_name_plural': 'controles em processo da OP',
                'ordering': ['data', 'id'],
            },
        ),
    ]
