# Generated by Django 5.2.16 on 2026-07-20 20:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def ocorrencias_para_desvios(apps, schema_editor):
    """
    Migra ocorrências antigas (texto livre) para Desvios já ENCERRADOS —
    eram informativas e não devem bloquear o encerramento de OPs.
    """
    Ocorrencia = apps.get_model("producao", "Ocorrencia")
    Desvio = apps.get_model("producao", "Desvio")

    for ocorrencia in Ocorrencia.objects.select_related("execucao__ordem"):
        Desvio.objects.create(
            ordem=ocorrencia.execucao.ordem,
            tipo="OUTRO",
            descricao=ocorrencia.descricao,
            responsavel_id=ocorrencia.registrado_por_id,
            status="ENCERRADO",
            criado_em=ocorrencia.data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_etapasnapshotop_etapaformula'),
        ('producao', '0007_controleprocessoop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('PROCESSO', 'Processo'), ('MATERIAL', 'Material'), ('EQUIPAMENTO', 'Equipamento'), ('DOCUMENTACAO', 'Documentação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=15, verbose_name='tipo')),
                ('etapa', models.CharField(blank=True, max_length=120, verbose_name='etapa')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('impacto', models.TextField(blank=True, verbose_name='impacto')),
                ('acao_imediata', models.TextField(blank=True, verbose_name='ação imediata')),
                ('critico', models.BooleanField(default=False, verbose_name='desvio crítico')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('EM_AVALIACAO', 'Em avaliação'), ('ENCERRADO', 'Encerrado')], default='ABERTO', max_length=15, verbose_name='situação')),
                ('decisao', models.CharField(blank=True, choices=[('ACEITO', 'Aceito (segue produção)'), ('RETRABALHO', 'Retrabalho'), ('REPROVADO', 'Reprovado (bloquear lote)')], max_length=15, verbose_name='decisão')),
                ('decidido_em', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('justificativa_decisao', models.TextField(blank=True, verbose_name='justificativa da decisão')),
                ('capa', models.CharField(blank=True, help_text='Referência de NC/CAPA, quando houver.', max_length=120, verbose_name='não conformidade / CAPA')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='avaliador')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='desvios', to='ordens.ordemproducao', verbose_name='ordem de produção')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'desvio',
                'verbose_name_plural': 'desvios',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.RunPython(ocorrencias_para_desvios, migrations.RunPython.noop),
    ]
