# Generated by Django 5.2.16 on 2026-07-21 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producao', '0008_desvio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='execucaoop',
            name='perda_aprovada_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='perda aprovada por'),
        ),
        migrations.AddField(
            model_name='execucaoop',
            name='perda_justificativa',
            field=models.TextField(blank=True, verbose_name='justificativa da perda'),
        ),
        migrations.AddField(
            model_name='execucaoop',
            name='perda_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='perda (%)'),
        ),
        migrations.AddField(
            model_name='execucaoop',
            name='quantidade_teorica',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='quantidade teórica'),
        ),
        migrations.AddField(
            model_name='execucaoop',
            name='rendimento_percentual',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='rendimento (%)'),
        ),
    ]
