# Generated by Django 5.2.16 on 2026-07-21 22:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_versaoarte'),
        ('estoque', '0003_lote_situacao'),
        ('ordens', '0005_etapasnapshotop_etapaformula'),
        ('producao', '0009_execucaoop_perda_aprovada_por_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvaseOP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True, verbose_name='início')),
                ('fim', models.DateTimeField(blank=True, null=True, verbose_name='fim')),
                ('quantidade_envasada', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='quantidade envasada')),
                ('peso_volume_medio', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='peso/volume médio')),
                ('perdas', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12, verbose_name='perdas')),
                ('controles', models.TextField(blank=True, verbose_name='controles')),
                ('registrado_em', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
                ('conferente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='conferente')),
                ('linha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cadastros.setor', verbose_name='linha')),
                ('lote_granel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.lote', verbose_name='lote do granel')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='operador')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envases', to='ordens.ordemproducao', verbose_name='ordem de produção')),
                ('versao_arte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envases', to='cadastros.versaoarte', verbose_name='versão de arte')),
            ],
            options={
                'verbose_name': 'envase da OP',
                'verbose_name_plural': 'envases da OP',
                'ordering': ['registrado_em', 'id'],
            },
        ),
    ]
