# Generated by Django 5.2.16 on 2026-07-21 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0005_etapasnapshotop_etapaformula'),
        ('producao', '0010_envaseop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiberacaoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('EMISSAO', 'Emissão'), ('SEPARACAO', 'Separação'), ('PESAGEM', 'Pesagem'), ('CONFERENCIA', 'Conferência'), ('PRODUCAO', 'Produção'), ('ENCERRAMENTO', 'Encerramento'), ('ANALISE', 'Análise / CQ'), ('APROVACAO', 'Aprovação'), ('LIBERACAO_TECNICA', 'Liberação técnica')], max_length=20, verbose_name='fase')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='observação')),
                ('ordem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liberacoes_fase', to='ordens.ordemproducao', verbose_name='ordem de produção')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'assinatura de fase da OP',
                'verbose_name_plural': 'assinaturas de fase da OP',
                'ordering': ['data', 'id'],
            },
        ),
    ]
