# Generated by Django 5.2.16 on 2026-07-12 00:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'local de estoque',
                'verbose_name_plural': 'locais de estoque',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('codigo', models.CharField(max_length=50, verbose_name='código do lote')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('embalagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='cadastros.embalagem', verbose_name='embalagem')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='cadastros.materiaprima', verbose_name='matéria-prima')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='cadastros.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['validade', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('TRANSFERENCIA', 'Transferência'), ('AJUSTE_ENTRADA', 'Ajuste de inventário (+)'), ('AJUSTE_SAIDA', 'Ajuste de inventário (−)')], max_length=20, verbose_name='tipo')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('motivo', models.CharField(max_length=200, verbose_name='motivo')),
                ('documento', models.CharField(blank=True, help_text='Ex.: número da NF, da OP ou do inventário.', max_length=60, verbose_name='documento de referência')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('embalagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.embalagem', verbose_name='embalagem')),
                ('local_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_de_entrada', to='estoque.localestoque', verbose_name='local de destino')),
                ('local_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_de_saida', to='estoque.localestoque', verbose_name='local de origem')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='estoque.lote', verbose_name='lote')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.materiaprima', verbose_name='matéria-prima')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes', to='cadastros.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'movimentação',
                'verbose_name_plural': 'movimentações',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('produto__isnull', False), ('materia_prima__isnull', True), ('embalagem__isnull', True)), models.Q(('produto__isnull', True), ('materia_prima__isnull', False), ('embalagem__isnull', True)), models.Q(('produto__isnull', True), ('materia_prima__isnull', True), ('embalagem__isnull', False)), _connector='OR'), name='lote_exatamente_um_item'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(condition=models.Q(('produto__isnull', False)), fields=('produto', 'codigo'), name='lote_unico_por_produto'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(condition=models.Q(('materia_prima__isnull', False)), fields=('materia_prima', 'codigo'), name='lote_unico_por_materia_prima'),
        ),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(condition=models.Q(('embalagem__isnull', False)), fields=('embalagem', 'codigo'), name='lote_unico_por_embalagem'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['tipo'], name='estoque_mov_tipo_f0fdc8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimentacao',
            index=models.Index(fields=['criado_em'], name='estoque_mov_criado__cfefec_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimentacao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('produto__isnull', False), ('materia_prima__isnull', True), ('embalagem__isnull', True)), models.Q(('produto__isnull', True), ('materia_prima__isnull', False), ('embalagem__isnull', True)), models.Q(('produto__isnull', True), ('materia_prima__isnull', True), ('embalagem__isnull', False)), _connector='OR'), name='movimentacao_exatamente_um_item'),
        ),
    ]
