# Generated by Django 5.2.16 on 2026-07-19 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='lote_fornecedor',
            field=models.CharField(blank=True, help_text='Código impresso pelo fornecedor na embalagem/laudo.', max_length=60, verbose_name='lote do fornecedor'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='lote interno'),
        ),
        migrations.CreateModel(
            name='SequenciaLote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=3, verbose_name='tipo')),
                ('ano', models.PositiveIntegerField(verbose_name='ano')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, verbose_name='último número')),
            ],
            options={
                'verbose_name': 'sequência de lote interno',
                'verbose_name_plural': 'sequências de lote interno',
                'constraints': [models.UniqueConstraint(fields=('tipo', 'ano'), name='sequencia_lote_unica_por_tipo_ano')],
            },
        ),
    ]
