# Generated by Django 5.2.16 on 2026-07-20 16:04

from django.db import migrations, models

# Decisão da quarentena → situação do lote (Etapa 5). Mantido literal
# aqui porque migrações não devem importar do código da app.
SITUACAO_POR_DECISAO = {
    "EM_QUARENTENA": "AGUARDANDO_CQ",
    "EM_ANALISE": "EM_ANALISE",
    "LIBERADO": "APROVADO",
    "REPROVADO": "REPROVADO",
    "BLOQUEADO": "BLOQUEADO",
    "DEVOLVIDO": "DEVOLVIDO",
}


def backfill_situacao(apps, schema_editor):
    """
    Lotes existentes: situação a partir da decisão de quarentena mais
    recente. Sem decisão, mantém o default (AGUARDANDO_CQ).
    """
    Lote = apps.get_model("estoque", "Lote")
    DecisaoQuarentena = apps.get_model("recebimento", "DecisaoQuarentena")

    for lote in Lote.objects.all():
        decisao = (
            DecisaoQuarentena.objects.filter(item__lote=lote)
            .order_by("-data", "-id")
            .first()
        )
        if decisao is None:
            continue
        situacao = SITUACAO_POR_DECISAO.get(decisao.decisao)
        if situacao and situacao != lote.situacao:
            lote.situacao = situacao
            lote.save(update_fields=["situacao"])


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0002_lote_lote_fornecedor_alter_lote_codigo_sequencialote'),
        ('recebimento', '0002_recebimento_cliente_alter_decisaoquarentena_decisao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='situacao',
            field=models.CharField(choices=[('EM_PRODUCAO', 'Em produção'), ('AGUARDANDO_CQ', 'Aguardando CQ'), ('EM_ANALISE', 'Em análise'), ('APROVADO', 'Aprovado'), ('REPROVADO', 'Reprovado'), ('BLOQUEADO', 'Bloqueado'), ('EXPEDIDO', 'Expedido'), ('RECOLHIDO', 'Recolhido'), ('DEVOLVIDO', 'Devolvido')], default='AGUARDANDO_CQ', max_length=20, verbose_name='situação'),
        ),
        migrations.RunPython(backfill_situacao, migrations.RunPython.noop),
    ]
