# Generated by Django 5.2.16 on 2026-07-12 13:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('status', models.CharField(choices=[('EM_QUARENTENA', 'Em quarentena'), ('LIBERADO', 'Liberado'), ('REPROVADO', 'Reprovado'), ('BLOQUEADO', 'Bloqueado')], default='EM_QUARENTENA', max_length=20, verbose_name='situação')),
                ('embalagem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_recebimento', to='cadastros.embalagem', verbose_name='embalagem')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_recebimento', to='estoque.lote', verbose_name='lote')),
                ('materia_prima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_recebimento', to='cadastros.materiaprima', verbose_name='matéria-prima')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itens_de_recebimento', to='cadastros.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'item do recebimento',
                'verbose_name_plural': 'itens do recebimento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DecisaoQuarentena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decisao', models.CharField(choices=[('EM_QUARENTENA', 'Em quarentena'), ('LIBERADO', 'Liberado'), ('REPROVADO', 'Reprovado'), ('BLOQUEADO', 'Bloqueado')], max_length=20, verbose_name='decisão')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('local_destino', models.ForeignKey(blank=True, help_text='Para onde o material foi na liberação.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.localestoque', verbose_name='local de destino')),
                ('responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='recebimento.itemrecebimento', verbose_name='item')),
            ],
            options={
                'verbose_name': 'decisão de quarentena',
                'verbose_name_plural': 'decisões de quarentena',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Recebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('nota_fiscal', models.CharField(max_length=60, verbose_name='nota fiscal')),
                ('data_recebimento', models.DateField(default=django.utils.timezone.localdate, verbose_name='data do recebimento')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='cadastros.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'recebimento',
                'verbose_name_plural': 'recebimentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='itemrecebimento',
            name='recebimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='recebimento.recebimento', verbose_name='recebimento'),
        ),
        migrations.CreateModel(
            name='AnexoRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('tipo', models.CharField(choices=[('COA', 'COA (Certificado de Análise)'), ('FISPQ', 'FISPQ'), ('FOTO', 'Foto'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='tipo')),
                ('arquivo', models.FileField(help_text='PDF ou imagem (JPG, PNG, WEBP).', upload_to='recebimentos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='arquivo')),
                ('descricao', models.CharField(blank=True, max_length=120, verbose_name='descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('recebimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='recebimento.recebimento', verbose_name='recebimento')),
            ],
            options={
                'verbose_name': 'anexo do recebimento',
                'verbose_name_plural': 'anexos do recebimento',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemrecebimento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('produto__isnull', False), ('materia_prima__isnull', True), ('embalagem__isnull', True)), models.Q(('produto__isnull', True), ('materia_prima__isnull', False), ('embalagem__isnull', True)), models.Q(('produto__isnull', True), ('materia_prima__isnull', True), ('embalagem__isnull', False)), _connector='OR'), name='item_recebimento_exatamente_um_item'),
        ),
    ]
