# Generated by Django 5.2.16 on 2026-07-19 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        ('recebimento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recebimento',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Preencha quando o material pertence a um cliente — sai na etiqueta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recebimentos', to='cadastros.cliente', verbose_name='cliente (terceirização)'),
        ),
        migrations.AlterField(
            model_name='decisaoquarentena',
            name='decisao',
            field=models.CharField(choices=[('EM_QUARENTENA', 'Em quarentena'), ('EM_ANALISE', 'Em análise'), ('LIBERADO', 'Liberado'), ('REPROVADO', 'Reprovado'), ('BLOQUEADO', 'Bloqueado'), ('DEVOLVIDO', 'Devolvido')], max_length=20, verbose_name='decisão'),
        ),
        migrations.AlterField(
            model_name='itemrecebimento',
            name='status',
            field=models.CharField(choices=[('EM_QUARENTENA', 'Em quarentena'), ('EM_ANALISE', 'Em análise'), ('LIBERADO', 'Liberado'), ('REPROVADO', 'Reprovado'), ('BLOQUEADO', 'Bloqueado'), ('DEVOLVIDO', 'Devolvido')], default='EM_QUARENTENA', max_length=20, verbose_name='situação'),
        ),
    ]
