# Generated by Django 5.2.16 on 2026-07-11 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Embalagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro')], default='UN', max_length=2, verbose_name='unidade')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Abaixo desta quantidade o item aparece como estoque crítico.', max_digits=12, verbose_name='estoque mínimo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('tipo', models.CharField(choices=[('FRASCO', 'Frasco'), ('TAMPA', 'Tampa'), ('VALVULA', 'Válvula'), ('ROTULO', 'Rótulo'), ('CAIXA', 'Caixa'), ('OUTRO', 'Outro')], default='OUTRO', max_length=10, verbose_name='tipo')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'embalagem',
                'verbose_name_plural': 'embalagens',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro')], default='UN', max_length=2, verbose_name='unidade')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Abaixo desta quantidade o item aparece como estoque crítico.', max_digits=12, verbose_name='estoque mínimo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'matéria-prima',
                'verbose_name_plural': 'matérias-primas',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('unidade', models.CharField(choices=[('UN', 'Unidade'), ('CX', 'Caixa'), ('KG', 'Quilograma'), ('G', 'Grama'), ('L', 'Litro'), ('ML', 'Mililitro')], default='UN', max_length=2, verbose_name='unidade')),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, help_text='Abaixo desta quantidade o item aparece como estoque crítico.', max_digits=12, verbose_name='estoque mínimo')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'produto',
                'verbose_name_plural': 'produtos',
                'ordering': ['nome'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'setor',
                'verbose_name_plural': 'setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('capacidade', models.DecimalField(blank=True, decimal_places=3, help_text='Capacidade por lote ou por hora, conforme a unidade informada.', max_digits=12, null=True, verbose_name='capacidade')),
                ('unidade_capacidade', models.CharField(blank=True, help_text='Ex.: kg/lote, L/h, un/h.', max_length=20, verbose_name='unidade da capacidade')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('setor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipamentos', to='cadastros.setor', verbose_name='setor')),
            ],
            options={
                'verbose_name': 'equipamento',
                'verbose_name_plural': 'equipamentos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('razao_social', models.CharField(max_length=150, verbose_name='razão social / nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, verbose_name='nome fantasia')),
                ('documento', models.CharField(blank=True, help_text='Somente números ou com máscara; usado em notas e relatórios.', max_length=18, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['razao_social'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('documento',), name='cliente_documento_unico', violation_error_message='Já existe um cliente com este CNPJ/CPF.')],
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('razao_social', models.CharField(max_length=150, verbose_name='razão social / nome')),
                ('nome_fantasia', models.CharField(blank=True, max_length=150, verbose_name='nome fantasia')),
                ('documento', models.CharField(blank=True, help_text='Somente números ou com máscara; usado em notas e relatórios.', max_length=18, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['razao_social'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('documento',), name='fornecedor_documento_unico', violation_error_message='Já existe um fornecedor com este CNPJ/CPF.')],
            },
        ),
    ]
