# Generated by Django 5.2.16 on 2026-07-11 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrar_contatos_legados(apps, schema_editor):
    Cliente = apps.get_model('cadastros', 'Cliente')
    Fornecedor = apps.get_model('cadastros', 'Fornecedor')
    ClienteEndereco = apps.get_model('cadastros', 'ClienteEndereco')
    ClienteTelefone = apps.get_model('cadastros', 'ClienteTelefone')
    FornecedorEndereco = apps.get_model('cadastros', 'FornecedorEndereco')
    FornecedorTelefone = apps.get_model('cadastros', 'FornecedorTelefone')

    for cliente in Cliente.objects.all():
        if cliente.telefone:
            ClienteTelefone.objects.create(
                cliente_id=cliente.pk,
                telefone=cliente.telefone,
                principal=True,
                criado_por_id=cliente.criado_por_id,
                atualizado_por_id=cliente.atualizado_por_id,
            )
        if cliente.endereco or cliente.cidade or cliente.uf or cliente.cep:
            ClienteEndereco.objects.create(
                cliente_id=cliente.pk,
                cep=cliente.cep,
                logradouro=cliente.endereco or "Endereço não informado",
                cidade=cliente.cidade,
                uf=cliente.uf,
                principal=True,
                criado_por_id=cliente.criado_por_id,
                atualizado_por_id=cliente.atualizado_por_id,
            )

    for fornecedor in Fornecedor.objects.all():
        if fornecedor.telefone:
            FornecedorTelefone.objects.create(
                fornecedor_id=fornecedor.pk,
                telefone=fornecedor.telefone,
                principal=True,
                criado_por_id=fornecedor.criado_por_id,
                atualizado_por_id=fornecedor.atualizado_por_id,
            )
        if fornecedor.endereco or fornecedor.cidade or fornecedor.uf or fornecedor.cep:
            FornecedorEndereco.objects.create(
                fornecedor_id=fornecedor.pk,
                cep=fornecedor.cep,
                logradouro=fornecedor.endereco or "Endereço não informado",
                cidade=fornecedor.cidade,
                uf=fornecedor.uf,
                principal=True,
                criado_por_id=fornecedor.criado_por_id,
                atualizado_por_id=fornecedor.atualizado_por_id,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('ENTREGA', 'Entrega'), ('COBRANCA', 'Cobrança'), ('RESIDENCIAL', 'Residencial'), ('OUTRO', 'Outro')], default='COMERCIAL', max_length=20, verbose_name='tipo')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=150, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=80, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('observacoes', models.CharField(blank=True, max_length=150, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastros.cliente', verbose_name='cliente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'endereço do cliente',
                'verbose_name_plural': 'endereços do cliente',
                'ordering': ['-principal', 'tipo', 'logradouro'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('principal', True)), fields=('cliente',), name='cliente_endereco_principal_unico', violation_error_message='Marque apenas um endereço principal.')],
            },
        ),
        migrations.CreateModel(
            name='ClienteTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('CELULAR', 'Celular'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('RESIDENCIAL', 'Residencial'), ('OUTRO', 'Outro')], default='COMERCIAL', max_length=20, verbose_name='tipo')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='contato')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('observacoes', models.CharField(blank=True, max_length=150, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='cadastros.cliente', verbose_name='cliente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'telefone do cliente',
                'verbose_name_plural': 'telefones do cliente',
                'ordering': ['-principal', 'tipo', 'telefone'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('principal', True)), fields=('cliente',), name='cliente_telefone_principal_unico', violation_error_message='Marque apenas um telefone principal.')],
            },
        ),
        migrations.CreateModel(
            name='FornecedorEndereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('ENTREGA', 'Entrega'), ('COBRANCA', 'Cobrança'), ('RESIDENCIAL', 'Residencial'), ('OUTRO', 'Outro')], default='COMERCIAL', max_length=20, verbose_name='tipo')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=150, verbose_name='logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('complemento', models.CharField(blank=True, max_length=80, verbose_name='complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('uf', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('observacoes', models.CharField(blank=True, max_length=150, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='cadastros.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'endereço do fornecedor',
                'verbose_name_plural': 'endereços do fornecedor',
                'ordering': ['-principal', 'tipo', 'logradouro'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('principal', True)), fields=('fornecedor',), name='fornecedor_endereco_principal_unico', violation_error_message='Marque apenas um endereço principal.')],
            },
        ),
        migrations.CreateModel(
            name='FornecedorTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('CELULAR', 'Celular'), ('COMERCIAL', 'Comercial'), ('FINANCEIRO', 'Financeiro'), ('RESIDENCIAL', 'Residencial'), ('OUTRO', 'Outro')], default='COMERCIAL', max_length=20, verbose_name='tipo')),
                ('telefone', models.CharField(max_length=20, verbose_name='telefone')),
                ('contato', models.CharField(blank=True, max_length=100, verbose_name='contato')),
                ('principal', models.BooleanField(default=False, verbose_name='principal')),
                ('observacoes', models.CharField(blank=True, max_length=150, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='cadastros.fornecedor', verbose_name='fornecedor')),
            ],
            options={
                'verbose_name': 'telefone do fornecedor',
                'verbose_name_plural': 'telefones do fornecedor',
                'ordering': ['-principal', 'tipo', 'telefone'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('principal', True)), fields=('fornecedor',), name='fornecedor_telefone_principal_unico', violation_error_message='Marque apenas um telefone principal.')],
            },
        ),
        migrations.RunPython(migrar_contatos_legados, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='cliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='uf',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='fornecedor',
            name='uf',
        ),
    ]
