# Generated by Django 5.2.16 on 2026-07-20 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_remove_cliente_cep_remove_cliente_cidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='critico',
            field=models.BooleanField(default=False, help_text='Exige dupla conferência na pesagem (conferente ≠ operador).', verbose_name='material crítico'),
        ),
        migrations.CreateModel(
            name='Balanca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('descricao', models.CharField(max_length=120, verbose_name='descrição')),
                ('capacidade', models.DecimalField(blank=True, decimal_places=3, help_text='Capacidade máxima, na unidade de pesagem.', max_digits=12, null=True, verbose_name='capacidade')),
                ('unidade_capacidade', models.CharField(blank=True, help_text='Ex.: kg, g.', max_length=20, verbose_name='unidade da capacidade')),
                ('calibracao_validade', models.DateField(blank=True, null=True, verbose_name='validade da calibração')),
                ('localizacao', models.CharField(blank=True, max_length=100, verbose_name='localização')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'balança',
                'verbose_name_plural': 'balanças',
                'ordering': ['codigo'],
            },
        ),
    ]
