# Generated by Django 5.2.16 on 2026-07-20 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_materiaprima_critico_balanca'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='calibracao_validade',
            field=models.DateField(blank=True, null=True, verbose_name='validade da calibração'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='localização'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='manutencao_validade',
            field=models.DateField(blank=True, null=True, verbose_name='validade da manutenção'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('LIBERADO', 'Liberado'), ('MANUTENCAO', 'Em manutenção'), ('INTERDITADO', 'Interditado')], default='LIBERADO', max_length=15, verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ultima_limpeza',
            field=models.DateField(blank=True, null=True, verbose_name='última limpeza'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ultima_sanitizacao',
            field=models.DateField(blank=True, null=True, verbose_name='última sanitização'),
        ),
    ]
