# Generated by Django 5.2.16 on 2026-07-21 22:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_equipamento_calibracao_validade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='limite_perda_percentual',
            field=models.DecimalField(decimal_places=3, default=Decimal('5'), help_text='Perda acima deste percentual exige justificativa e aprovação.', max_digits=6, verbose_name='limite de perda (%)'),
        ),
    ]
