# Generated by Django 5.2.16 on 2026-07-21 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_produto_limite_perda_percentual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VersaoArte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('versao', models.CharField(max_length=30, verbose_name='versão')),
                ('data_aprovacao', models.DateField(blank=True, null=True, verbose_name='data de aprovação')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='artes/%Y/%m/', verbose_name='arquivo da arte')),
                ('status', models.CharField(choices=[('APROVADA', 'Aprovada'), ('OBSOLETA', 'Obsoleta')], default='APROVADA', max_length=10, verbose_name='situação')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versoes_arte', to='cadastros.produto', verbose_name='produto')),
            ],
            options={
                'verbose_name': 'versão de arte',
                'verbose_name_plural': 'versões de arte',
                'ordering': ['produto__nome', '-versao'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'versao'), name='versao_arte_unica_por_produto', violation_error_message='Este produto já tem essa versão de arte.')],
            },
        ),
    ]
