# Generated by Django 5.2.16 on 2026-07-22 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_versaoarte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Cliente bloqueado não pode receber novos pedidos.', verbose_name='cliente bloqueado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='motivo_bloqueio',
            field=models.CharField(blank=True, max_length=200, verbose_name='motivo do bloqueio'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsavel_tecnico',
            field=models.CharField(blank=True, max_length=150, verbose_name='responsável técnico'),
        ),
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('tipo', models.CharField(choices=[('AFE', 'AFE (Autorização de Funcionamento)'), ('ALVARA', 'Alvará sanitário'), ('LICENCA', 'Licença de funcionamento'), ('CONTRATO', 'Contrato'), ('REGISTRO', 'Registro / notificação de produto'), ('OUTRO', 'Outro')], default='OUTRO', max_length=15, verbose_name='tipo')),
                ('numero', models.CharField(blank=True, max_length=80, verbose_name='número')),
                ('orgao_emissor', models.CharField(blank=True, max_length=120, verbose_name='órgão emissor')),
                ('emissao', models.DateField(blank=True, null=True, verbose_name='emissão')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='validade')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='documentos_cliente/%Y/%m/', verbose_name='arquivo')),
                ('observacoes', models.CharField(blank=True, max_length=200, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='cadastros.cliente', verbose_name='cliente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'documento do cliente',
                'verbose_name_plural': 'documentos do cliente',
                'ordering': ['validade', 'tipo'],
            },
        ),
    ]
