# Generated by Django 5.2.16 on 2026-07-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_cliente_bloqueado_cliente_motivo_bloqueio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='apresentacao',
            field=models.CharField(blank=True, help_text='Ex.: frasco 100 ml, bisnaga 80 g.', max_length=120, verbose_name='apresentação'),
        ),
        migrations.AddField(
            model_name='produto',
            name='bloqueado',
            field=models.BooleanField(default=False, help_text='Produto bloqueado não gera novas ordens de produção.', verbose_name='produto bloqueado'),
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(blank=True, max_length=80, verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='produto',
            name='grau',
            field=models.CharField(blank=True, choices=[('GRAU_1', 'Grau 1'), ('GRAU_2', 'Grau 2')], max_length=10, verbose_name='grau'),
        ),
        migrations.AddField(
            model_name='produto',
            name='motivo_bloqueio',
            field=models.CharField(blank=True, max_length=200, verbose_name='motivo do bloqueio'),
        ),
        migrations.AddField(
            model_name='produto',
            name='registro_anvisa',
            field=models.CharField(blank=True, max_length=60, verbose_name='registro/processo ANVISA'),
        ),
        migrations.AddField(
            model_name='produto',
            name='situacao_regulatoria',
            field=models.CharField(choices=[('REGULARIZADO', 'Regularizado'), ('ISENTO', 'Isento de registro'), ('EM_ANALISE', 'Em análise na ANVISA'), ('VENCIDO', 'Registro vencido')], default='REGULARIZADO', max_length=15, verbose_name='situação regulatória'),
        ),
    ]
