# Generated by Django 5.2.16 on 2026-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_produto_apresentacao_produto_bloqueado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiaprima',
            name='cas',
            field=models.CharField(blank=True, max_length=40, verbose_name='número CAS'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='condicoes_armazenamento',
            field=models.CharField(blank=True, max_length=200, verbose_name='condições de armazenamento'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='especificacao',
            field=models.TextField(blank=True, verbose_name='especificação'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='ficha_tecnica',
            field=models.FileField(blank=True, null=True, upload_to='fichas_mp/%Y/%m/', verbose_name='ficha técnica'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='fispq',
            field=models.FileField(blank=True, null=True, upload_to='fispq/%Y/%m/', verbose_name='FISPQ'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='fornecedores_aprovados',
            field=models.ManyToManyField(blank=True, help_text='Se preenchido, só lotes desses fornecedores podem ser consumidos.', related_name='materias_primas_aprovadas', to='cadastros.fornecedor', verbose_name='fornecedores aprovados'),
        ),
        migrations.AddField(
            model_name='materiaprima',
            name='inci',
            field=models.CharField(blank=True, max_length=150, verbose_name='nome INCI'),
        ),
    ]
