# Generated by Django 5.2.16 on 2026-07-22 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_materiaprima_cas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='embalagem',
            name='capacidade',
            field=models.CharField(blank=True, help_text='Ex.: 100 ml, 80 g.', max_length=60, verbose_name='capacidade'),
        ),
        migrations.AddField(
            model_name='embalagem',
            name='cor',
            field=models.CharField(blank=True, max_length=60, verbose_name='cor'),
        ),
        migrations.AddField(
            model_name='embalagem',
            name='fabricante',
            field=models.CharField(blank=True, max_length=150, verbose_name='fabricante'),
        ),
        migrations.AddField(
            model_name='embalagem',
            name='fornecedores_aprovados',
            field=models.ManyToManyField(blank=True, help_text='Se preenchido, só lotes desses fornecedores podem ser consumidos.', related_name='embalagens_aprovadas', to='cadastros.fornecedor', verbose_name='fornecedores aprovados'),
        ),
        migrations.AddField(
            model_name='embalagem',
            name='inspecao',
            field=models.TextField(blank=True, help_text='O que conferir no recebimento (dimensões, impressão, vedação).', verbose_name='critérios de inspeção'),
        ),
        migrations.AddField(
            model_name='embalagem',
            name='material',
            field=models.CharField(blank=True, help_text='Ex.: PET, vidro, PP.', max_length=80, verbose_name='material'),
        ),
        migrations.AddField(
            model_name='embalagem',
            name='versao_arte',
            field=models.ForeignKey(blank=True, help_text='Para rótulos: arte vinculada. Arte obsoleta bloqueia o uso na OP.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='embalagens', to='cadastros.versaoarte', verbose_name='versão de arte'),
        ),
    ]
