# Generated by Django 5.2.16 on 2026-07-22 11:44

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0003_lote_situacao'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('data', models.DateField(verbose_name='data da expedição')),
                ('nota_fiscal', models.CharField(blank=True, max_length=60, verbose_name='nota fiscal')),
                ('transportadora', models.CharField(blank=True, max_length=120, verbose_name='transportadora')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('conferente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='conferente')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedicoes', to='pedidos.pedido', verbose_name='pedido')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
            ],
            options={
                'verbose_name': 'expedição',
                'verbose_name_plural': 'expedições',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemExpedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='quantidade')),
                ('expedicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='expedicao.expedicao', verbose_name='expedição')),
                ('item_pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedicoes', to='pedidos.itempedido', verbose_name='item do pedido')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expedicoes', to='estoque.lote', verbose_name='lote acabado')),
                ('movimentacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='estoque.movimentacao', verbose_name='movimentação de saída')),
            ],
            options={
                'verbose_name': 'item da expedição',
                'verbose_name_plural': 'itens da expedição',
                'ordering': ['id'],
            },
        ),
    ]
