# Generated by Django 5.2.16 on 2026-07-22 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0003_lote_situacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeracaoDossie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.PositiveIntegerField(verbose_name='versão')),
                ('gerado_em', models.DateTimeField(auto_now_add=True, verbose_name='gerado em')),
                ('hash_arquivo', models.CharField(max_length=64, verbose_name='hash SHA-256')),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='dossies/%Y/%m/', verbose_name='PDF do dossiê')),
                ('gerado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='gerado por')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dossies', to='estoque.lote', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'geração do dossiê',
                'verbose_name_plural': 'gerações do dossiê',
                'ordering': ['-gerado_em', '-id'],
                'constraints': [models.UniqueConstraint(fields=('lote', 'versao'), name='dossie_versao_unica_por_lote')],
            },
        ),
    ]
