# Generated by Django 5.2.16 on 2026-07-12 18:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('EM_ANALISE', 'Em análise'), ('APROVADA', 'Aprovada'), ('REPROVADA', 'Reprovada')], default='EM_ANALISE', max_length=20, verbose_name='situação')),
                ('observacoes', models.TextField(blank=True, verbose_name='observações')),
                ('decidido_em', models.DateTimeField(blank=True, null=True, verbose_name='decidido em')),
                ('parecer', models.TextField(blank=True, verbose_name='parecer')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('decidido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decidido por')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='analises', to='estoque.lote', verbose_name='lote')),
            ],
            options={
                'verbose_name': 'análise',
                'verbose_name_plural': 'análises',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AnexoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('arquivo', models.FileField(help_text='PDF ou imagem (JPG, PNG, WEBP).', upload_to='analises/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png', 'webp'])], verbose_name='arquivo')),
                ('descricao', models.CharField(blank=True, max_length=120, verbose_name='descrição')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='qualidade.analise', verbose_name='análise')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'anexo da análise',
                'verbose_name_plural': 'anexos da análise',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TipoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('unidade', models.CharField(blank=True, help_text='Ex.: pH, g/mL, cP. Vazio para análises visuais/sensoriais.', max_length=20, verbose_name='unidade')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='valor mínimo de referência')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='valor máximo de referência')),
                ('referencia_texto', models.CharField(blank=True, help_text='Para análises qualitativas. Ex.: “Límpido, sem partículas”.', max_length=200, verbose_name='referência descritiva')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
            ],
            options={
                'verbose_name': 'tipo de análise',
                'verbose_name_plural': 'tipos de análise',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_numerico', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='valor numérico')),
                ('valor_texto', models.CharField(blank=True, help_text='Para análises qualitativas (aparência, odor...).', max_length=200, verbose_name='resultado descritivo')),
                ('analise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='qualidade.analise', verbose_name='análise')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resultados', to='qualidade.tipoanalise', verbose_name='tipo de análise')),
            ],
            options={
                'verbose_name': 'resultado',
                'verbose_name_plural': 'resultados',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('analise', 'tipo'), name='resultado_tipo_unico_por_analise', violation_error_message='Este tipo de análise já foi registrado.')],
            },
        ),
    ]
