# Generated by Django 5.2.16 on 2026-07-20 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_equipamento_calibracao_validade_and_more'),
        ('qualidade', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EspecificacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para inativar o registro em vez de excluí-lo.', verbose_name='ativo')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='valor mínimo')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='valor máximo')),
                ('referencia_texto', models.CharField(blank=True, max_length=200, verbose_name='referência descritiva')),
                ('atualizado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificacoes', to='cadastros.produto', verbose_name='produto')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='especificacoes', to='qualidade.tipoanalise', verbose_name='parâmetro')),
            ],
            options={
                'verbose_name': 'especificação do produto',
                'verbose_name_plural': 'especificações do produto',
                'ordering': ['produto__nome', 'tipo__nome'],
                'constraints': [models.UniqueConstraint(fields=('produto', 'tipo'), name='especificacao_unica_por_produto_tipo', violation_error_message='Este produto já tem limite para este parâmetro.')],
            },
        ),
    ]
