# Generated by Django 5.2.16 on 2026-07-21 23:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualidade', '0002_especificacaoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analise',
            name='amostra',
            field=models.CharField(blank=True, max_length=60, verbose_name='amostra'),
        ),
        migrations.AddField(
            model_name='analise',
            name='analise_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contra_analises', to='qualidade.analise', verbose_name='análise anterior'),
        ),
        migrations.AddField(
            model_name='analise',
            name='analista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='analista'),
        ),
        migrations.AddField(
            model_name='analise',
            name='data_coleta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='data da coleta'),
        ),
        migrations.AddField(
            model_name='analise',
            name='laudo',
            field=models.FileField(blank=True, null=True, upload_to='laudos/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='laudo / certificado'),
        ),
    ]
