# Generated by Django 5.2.16 on 2026-07-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='id do registro')),
                ('objeto_repr', models.CharField(blank=True, help_text='Texto do registro no momento da ação (ex.: “OP-00012 · Shampoo”).', max_length=200, verbose_name='identificação do registro')),
                ('acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('ALTERACAO', 'Alteração'), ('CANCELAMENTO', 'Cancelamento'), ('INATIVACAO', 'Inativação'), ('APROVACAO', 'Aprovação'), ('LIBERACAO', 'Liberação'), ('EXCECAO_BLOQUEIO', 'Exceção de bloqueio')], max_length=20, verbose_name='ação')),
                ('campo', models.CharField(blank=True, max_length=100, verbose_name='campo')),
                ('valor_anterior', models.TextField(blank=True, verbose_name='valor anterior')),
                ('valor_novo', models.TextField(blank=True, verbose_name='valor novo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='data')),
                ('justificativa', models.TextField(blank=True, verbose_name='justificativa')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype', verbose_name='tipo do registro')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vazio apenas em ações do próprio sistema (carga de dados).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-data', '-id'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='auditoria_r_content_6c2bdc_idx')],
            },
        ),
    ]
