# Generated by Django 5.2.16 on 2026-07-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroauditoria',
            name='acao',
            field=models.CharField(choices=[('CRIACAO', 'Criação'), ('ALTERACAO', 'Alteração'), ('CANCELAMENTO', 'Cancelamento'), ('INATIVACAO', 'Inativação'), ('APROVACAO', 'Aprovação'), ('LIBERACAO', 'Liberação'), ('EXCECAO_BLOQUEIO', 'Exceção de bloqueio'), ('IMPRESSAO', 'Impressão')], max_length=20, verbose_name='ação'),
        ),
    ]
